name: Build Binaries

on:
  workflow_dispatch:

jobs:
  # 1. Сборка для обычных компьютеров (Intel / AMD)
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build Binary (x86_64)
        run: |
          pyinstaller --onefile --clean --name netsearch-x86_64 main.py

      - name: Upload Artifact PC
        uses: actions/upload-artifact@v4
        with:
          name: netsearch-linux-x86_64
          path: dist/netsearch-x86_64

  # 2. Сборка для ARM (Телефоны / Termux / Raspberry Pi)
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Включаем эмуляцию процессора ARM через QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Запускаем сборку внутри контейнера с архитектурой ARM64
      - name: Build Binary (ARM64)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update -y
            apt-get install -y python3 python3-pip
            pip3 install --upgrade pip
            pip3 install pyinstaller
          run: |
            pyinstaller --onefile --clean --name netsearch-arm64 main.py

      - name: Upload Artifact ARM64
        uses: actions/upload-artifact@v4
        with:
          name: netsearch-linux-arm64
          path: dist/netsearch-arm64
